"""empty message

Revision ID: 15ac80bcf676
Revises: None
Create Date: 2015-01-26 09:32:16.600000

"""

# revision identifiers, used by Alembic.
revision = '15ac80bcf676'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
