"""empty message

Revision ID: 26aa3521fb32
Revises: None
Create Date: 2015-01-26 09:35:13.843000

"""

# revision identifiers, used by Alembic.
revision = '26aa3521fb32'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_status', sa.Integer(), nullable=True))
    op.drop_column('post', 'post_love_count')
    op.drop_column('post', 'post_comment_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_comment_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('post_love_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('post', 'post_status')
    ### end Alembic commands ###
