"""empty message

Revision ID: 2c1d28a8a505
Revises: 5217dc95f6c1
Create Date: 2015-01-22 16:12:57.203000

"""

# revision identifiers, used by Alembic.
revision = '2c1d28a8a505'
down_revision = '5217dc95f6c1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_relationships')
    op.alter_column('post', 'category_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.add_column('tag', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('tag', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.drop_column('tag', 'tag_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('tag', 'tag_id')
    op.drop_column('tag', 'post_id')
    op.alter_column('post', 'category_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.create_table('tag_relationships',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
