"""empty message

Revision ID: 372402b69254
Revises: 4c985a9fd120
Create Date: 2015-01-22 12:21:29.518000

"""

# revision identifiers, used by Alembic.
revision = '372402b69254'
down_revision = '4c985a9fd120'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'category_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
