"""empty message

Revision ID: 41ec70496b95
Revises: 2c1d28a8a505
Create Date: 2015-01-22 16:18:54.767000

"""

# revision identifiers, used by Alembic.
revision = '41ec70496b95'
down_revision = '2c1d28a8a505'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_name', sa.String(length=100), nullable=True))
    op.drop_column('tag', 'tag_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('tag', 'tag_name')
    ### end Alembic commands ###
