"""empty message

Revision ID: 4c985a9fd120
Revises: None
Create Date: 2015-01-21 20:46:17.468000

"""

# revision identifiers, used by Alembic.
revision = '4c985a9fd120'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('post_title', sa.String(length=120), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('post_excerpt', sa.Text(), nullable=True),
    sa.Column('post_content', sa.Text(), nullable=True),
    sa.Column('post_view_count', sa.Integer(), nullable=True),
    sa.Column('post_comment_count', sa.Integer(), nullable=True),
    sa.Column('post_love_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_title')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    ### end Alembic commands ###
